---
title: "USDA Data"
output: pdf
---

```{r libraries_datasets}

library(tidyverse)
library(readxl)

USDA_Education <- read_excel("~/Duke/Junior Year 23-24/Spring Semester/Compsci 216/Project/USDA_Education.xlsx")
USDA_PopulationEstimates <- read_excel("~/Duke/Junior Year 23-24/Spring Semester/Compsci 216/Project/USDA_PopulationEstimates.xlsx")
USDA_Unemployment <- read_excel("~/Duke/Junior Year 23-24/Spring Semester/Compsci 216/Project/USDA_Unemployment_Table.xlsx")

```

```{r narrowing_data}

#USDA Education reformatting and filtering for specific years
USDA_Education <- USDA_Education[-(1:2), ]
colnames(USDA_Education) <- unlist(USDA_Education[1, ]) 
USDA_Education <- USDA_Education[-1, ]  

vec_edu <- names(USDA_Education)
#vec_edu

cols_keep_edu <- c("Federal Information Processing Standard (FIPS) Code","State","Area name","Less than a high school diploma, 2017-21","High school diploma only, 2017-21", "Some college or associate's degree, 2017-21", "Bachelor's degree or higher, 2017-21", "Percent of adults with less than a high school diploma, 2017-21", "Percent of adults with a high school diploma only, 2017-21", "Percent of adults completing some college or associate's degree, 2017-21","Percent of adults with a bachelor's degree or higher, 2017-21")

cols_to_keep_edu <- intersect(names(USDA_Education), cols_keep_edu)
USDA_Education <- USDA_Education[, cols_to_keep_edu]

#USDA Population reformatting and filtering for specific years
USDA_PopulationEstimates <- USDA_PopulationEstimates[-(1:3), ]
colnames(USDA_PopulationEstimates) <- unlist(USDA_PopulationEstimates[1, ]) 
USDA_PopulationEstimates <- USDA_PopulationEstimates[-1, ] 

vec_pop <- names(USDA_PopulationEstimates)
#vec_pop

cols_keep_pop <- c("FIPStxt","State","Area_Name","CENSUS_2020_POP","POP_ESTIMATE_2020","POP_ESTIMATE_2021","POP_ESTIMATE_2022",
                   "BIRTHS_2020","BIRTHS_2021","BIRTHS_2022","DEATHS_2020","DEATHS_2021","DEATHS_2022")
cols_to_keep_pop <- intersect(names(USDA_PopulationEstimates), cols_to_keep_pop)
USDA_PopulationEstimates <- USDA_PopulationEstimates[, cols_to_keep_pop]

#USDA Unemployment reformatting and filtering for specific years
USDA_Unemployment <- USDA_Unemployment[-(1:3), ]
colnames(USDA_Unemployment) <- unlist(USDA_Unemployment[1, ]) 
USDA_Unemployment <- USDA_Unemployment[-1, ] 

vec_unem <- names(USDA_Unemployment)
vec_unem

cols_to_keep_unem <- c("FIPS_Code","State","Area_Name","Unemployment_rate_2018","Civilian_labor_force_2019","Employed_2019","Unemployed_2019",
                       "Unemployment_rate_2019","Civilian_labor_force_2020","Employed_2020","Unemployed_2020","Unemployment_rate_2020",
                       "Civilian_labor_force_2021","Employed_2021","Unemployed_2021","Unemployment_rate_2021","Civilian_labor_force_2022",
                       "Employed_2022","Unemployed_2022","Unemployment_rate_2022","Median_Household_Income_2021",
                       "Med_HH_Income_Percent_of_State_Total_2021")
cols_to_keep_unem <- intersect(names(USDA_Unemployment), cols_to_keep_unem)
USDA_Unemployment <- USDA_Unemployment[, cols_to_keep_unem]

```

```{r csv_write}

#writing the three dataframes to csv files

#USDA Education
file_path <- "~/Duke/Junior Year 23-24/Spring Semester/Compsci 216/Project/Cleaned Data/USDA_Education.csv"
write.csv(USDA_Education, file = file_path, row.names = FALSE)

#USDA Population Estimates
file_path <- "~/Duke/Junior Year 23-24/Spring Semester/Compsci 216/Project/Cleaned Data/USDA_PopulationEstimates.csv"
write.csv(USDA_Education, file = file_path, row.names = FALSE)

#USDA Unemployment
file_path <- "~/Duke/Junior Year 23-24/Spring Semester/Compsci 216/Project/Cleaned Data/USDA_Unemployment.csv"
write.csv(USDA_Education, file = file_path, row.names = FALSE)

```




